# Generated by Django 3.1.1 on 2020-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, verbose_name='Header')),
                ('shortDescription', models.CharField(blank=True, max_length=255, verbose_name='Short description')),
                ('fullDescription', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
