# Generated by Django 3.1.1 on 2020-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepost',
            name='status',
            field=models.CharField(choices=[('general', 'general'), ('football', 'football')], default='general', max_length=255, verbose_name='Status'),
        ),
    ]
