# Generated by Django 3.1.1 on 2020-09-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_basepost_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basepost',
            old_name='status',
            new_name='sport',
        ),
    ]
