# Generated by Django 3.1.1 on 2020-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200928_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50, verbose_name='Header')),
                ('shortDescription', models.CharField(blank=True, max_length=255, verbose_name='Short description')),
                ('fullDescription', models.TextField(blank=True, verbose_name='Full description')),
                ('sport', models.CharField(choices=[('football', 'football')], default='football', max_length=255, verbose_name='Status')),
                ('status', models.CharField(choices=[('active', 'active'), ('upcoming', 'upcoming'), ('past', 'past')], default='upcoming', max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterField(
            model_name='basepost',
            name='fullDescription',
            field=models.TextField(blank=True, verbose_name='Full description'),
        ),
    ]
