# Generated by Django 3.1.1 on 2020-09-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200928_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasePost',
            new_name='Post',
        ),
    ]
